# Generated by Django 4.2.6 on 2023-12-07 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='descripcion',
            field=models.TextField(help_text='Ingrese la descripción de la tarea.'),
        ),
        migrations.AlterField(
            model_name='task',
            name='titulo',
            field=models.CharField(help_text='Ingrese el título de la tarea.', max_length=255),
        ),
    ]
